package pages;

import java.awt.*;
import java.io.IOException;

public class templateImportPage extends pagesMain {
    public templateImportPage() throws AWTException, IOException {
    }

    public String chooseFile = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/mat-accordion/mat-expansion-panel/div/div/div/div/span[1]/input";
    public String importTemplate = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/mat-accordion/mat-expansion-panel/div/div/div/div/span[2]/button/span";
    public String validateAndSave = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/mat-accordion/mat-expansion-panel/div/div/div/div/span[3]/button/span";
    public String submit = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/mat-accordion/mat-expansion-panel/div/div/div/div/span[4]/button/span";
    public String client = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[5]/figure/mat-form-field/div/div[1]/div[3]/span";
    public String account = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[9]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String fundingSource = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[13]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String totalMV = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[17]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String sponserFirm = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[21]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String grpTmName = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[25]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String advisorName = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[25]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String advisorEmail = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[33]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String strategy = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[6]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String statePrefOpt = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[18]/figure/div/mat-form-field/div/div[1]/div[3]/input";
    public String maturity = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[22]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String yield = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[26]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String sector = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[30]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String esgPreference = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[34]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String creditQuantitySPInstr = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[38]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String taxState = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[7]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String shortTermTaxRate = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[11]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String longTermTaxRate = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[15]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String maxRealizedSTGains = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[19]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String yrsToTrans = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[23]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String stYIDRealizedGain = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[23]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String stYIDRealizedLoss = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[31]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String liYIDRealizedGain = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[35]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String liYIDRealizedLoss = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[39]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String carryForwardLosses = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[43]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String cashToRaise = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[47]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String fileName = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[8]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String importDate = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[12]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String importedBy = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[16]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String accountCode = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[20]/figure/mat-form-field/div/div[1]/div[3]/input";
    public String status = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[1]/mat-expansion-panel/div/div/mat-dialog-content/form/mat-grid-list/div/mat-grid-tile[24]/figure/div/div/button";
    public String loading = "/html/body/div[1]/app-root/app-layout/ng-http-loader/div/sk-chasing-dots";
    public String tableStatus1 = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[2]/mat-expansion-panel/div/div/div/mat-card/mat-tab-group/div/mat-tab-body[1]/div/div/app-tables-template/mat-dialog-content/div/mat-table/mat-row[1]/mat-cell[6]";
    public String tableStatus2 = "/html/body/div[1]/app-root/app-layout/mat-sidenav-container/mat-sidenav-content/div/app-import-template/div/div/mat-accordion[2]/mat-expansion-panel/div/div/div/mat-card/mat-tab-group/div/mat-tab-body[1]/div/div/app-tables-template/mat-dialog-content/div/mat-table/mat-row[2]/mat-cell[6]";
}

